### ISSUE TITLE
RuntimeError (Typelib file for namespace 'GnomeKeyring' (any version) not found)

### ISSUE THREAD

**Issue by HarlemSquirrel** [jheiss/keyring#10]
```
2.6.5 :001 > require 'keyring'
true
2.6.5 :002 > keyring = Keyring.new
Traceback (most recent call last):
       16: from ~/.rvm/gems/ruby-2.6.5/gems/keyring-0.4.1/lib/keyring/backend.rb:14:in `block in create'
       15: from ~/.rvm/gems/ruby-2.6.5/gems/keyring-0.4.1/lib/keyring/backend.rb:14:in `new'
       14: from ~/.rvm/gems/ruby-2.6.5/gems/keyring-0.4.1/lib/keyring/backends/gnome_keyring.rb:12:in `initialize'
       13: from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
       12: from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
       11: from ~/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
       10: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-gnome_keyring-0.0.10/lib/gir_ffi-gnome_keyring.rb:5:in `<top (required)>'
        9: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/gir_ffi/core.rb:29:in `setup'
        8: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/gir_ffi/builder.rb:42:in `build_module'
        7: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/gir_ffi/builders/module_builder.rb:23:in `generate'
        6: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/gir_ffi/builders/module_builder.rb:60:in `modul'
        5: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/gir_ffi/builders/module_builder.rb:69:in `build_dependencies'
        4: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/gir_ffi/builders/module_builder.rb:116:in `gir'
        3: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/gir_ffi/builders/module_builder.rb:116:in `tap'
        2: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/gir_ffi/builders/module_builder.rb:117:in `block in gir'
        1: from ~/.rvm/gems/ruby-2.6.5/gems/gir_ffi-0.13.1/lib/ffi-gobject_introspection/i_repository.rb:42:in `require'
RuntimeError (Typelib file for namespace 'GnomeKeyring' (any version) not found)
```

```
➤  lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne
```

**Comment by cyclotron3k** [comment]
I'm having this problem in Ruby 2.7.0 / Ubuntu 20.04

```
$ apt-get install gnome-keyring libgirepository1.0-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnome-keyring is already the newest version (3.36.0-1ubuntu1).
libgirepository1.0-dev is already the newest version (1.64.1-1~ubuntu20.04.1).
```

```
[1] pry(main)> require 'keyring'
=> true
[2] pry(main)> keyring = Keyring.new
RuntimeError: Typelib file for namespace 'GnomeKeyring' (any version) not found
from /var/lib/gems/2.7.0/gems/gir_ffi-0.15.3/lib/ffi-gobject_introspection/i_repository.rb:42:in `require'
Caused by LoadError: cannot load such file -- gir_ffi-gnome_keyring
from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

**EDIT** The problem seems to be coming from the [GirFFI](https://github.com/mvz/gir_ffi) dependency, see: https://github.com/mvz/gir_ffi-gnome_keyring/issues/6

**Comment by cyclotron3k** [comment]
See: mvz/gir_ffi-gnome_keyring#6

The problem seems to be the underlying operating system is no longer making GnomeKeyring available via GIR, and the required libraries aren't even available to be installed any more.
